### ISSUE TITLE
apollo-server-plugin-response-cache: cache hint not working

### ISSUE THREAD

**Issue by cherukumilli** [apollographql/apollo-server#3559]
My apollo graphql server setup uses the following:
```
    "apollo-datasource-rest": "^0.6.9",
    "apollo-server-express": "^2.9.12",
    "apollo-server-plugin-response-cache": "^0.3.8",
```

My schema:
```
type Query {
  types: [Type!]! @cacheControl(maxAge: 3600)
}

type Type {
  id: ID!
  label: String!
  active: Boolean!
}
```

My responseCachePlugin config:
```
responseCachePlugin({
    sessionId: (requestContext) => (requestContext.request.http.headers.get('sessionId') || null),
  })
```

### Neither the static cache hint like the above nor the dynamic cache hint in the resolver work. i.e., they don't cache the response from the datasource (REST API).

A bunch of other devs reported this issue on Spectrum. One of the Spectrum posts points to the problem:
```
The property requestContext.overallCachePolicy doesn't get updated by the cache hint, nither the static one in schema or the dynamic one ...
The value is always the cacheControl you configured when creating ApolloServer
```

**github link to the line in the code where there is a potential problem:**
https://github.com/apollographql/apollo-server/blob/1acf62d903253f5669c0c4f7255c8a87b95b5e6c/packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts#L243

**Spectrum post that details the above issue:**
https://spectrum.chat/apollo/apollo-server/apollo-server-plugin-response-cache-is-not-working-properly~e3390cd4-9e3f-4919-88b4-92508e235e38

Other Spectrum posts that talk about this problem:
1. https://spectrum.chat/apollo/apollo-server/cachecontrol-does-not-work-unless-defaultmaxage-is-set~0e4dc3c5-7cdc-40be-b833-0b2d436d1288
2. https://spectrum.chat/apollo/apollo-server/does-rediscache-work-in-dev-mode~18358268-8d11-4b13-a0c9-abddfb6623f3

cc to: @trevor-scheer

**Comment by Chuckatron** [comment]
I'm seeing exactly this problem also. I was working on adding response caching today and couldn't figure out why I wasn't seeing any caching happening. I'm glad I'm not going mad but also disappointed that caching is apparently broken :(

**Comment by HofmannZ** [comment]
Having the same issue, even without using the `apollo-server-plugin-response-cache` plugin.

**Comment by silentlight** [comment]
Having the same issue. Any idea how to solve it?

**Comment by ksaldana1** [comment]
Not seeing any responses get cached with `apollo-server-plugin-response-cache`, regardless of what I do with the directives and default config settings. I see the headers being set correctly, but that's pretty much it.

**Comment by leonardoanalista** [comment]
It's disappointing the cache only works if you set a global caching settings: 
```
  const server = new ApolloServer({
    cacheControl: {
       defaultMaxAge: 50,
    },
    plugins: [responseCachePlugin()],
    cache: new RedisCache({
      host: '127.0.0.1',
      namespace: 'apollo-cache:',
    }),
```

I am using `merge-graphql-schemas` with Redis and I am unable to get anything cached without the global settings.

I think it is a great idea to `@cacheControl` in the schema but it would be even better it it works first.

**Comment by elie222** [comment]
Have a similar problem. Some queries are cached. Others aren't.

Caching doesn't work when I do this:

```
cacheControl: {
    defaultMaxAge: 30,
  },
```

It does when I do:

```
cacheControl: true,
```

I've been testing cache hits through https://engine.apollographql.com/. Is there an easier way to do this?

**Comment by elie222** [comment]
The query that was cached fine doesn't use variables. The ones that didn't cache did. The variables didn't change but could this have caused a cache miss?

**Comment by ebubu** [comment]
The cache hint is actually working but not like expected.
The Max-Age value seems to be calculated from the smallest value found, **including** the defaultMaxAge.

So if you have a cache hint of 60 but your default is 10, the cache-control header will be set to 10.

[this bit of code explains this behavior](https://github.com/apollographql/apollo-server/blob/d5015f4ea00cadb2a74b09956344e6f65c084629/packages/apollo-cache-control/src/index.ts#L189)

**Comment by terryf82** [comment]
@Jylth  agree that the logic is not what you'd expect, but is technically [documented](https://www.apollographql.com/docs/apollo-server/performance/caching/#the-overall-cache-policy) correctly (but could probably be improved):

> Apollo Server then combines these hints into an overall cache policy for the response. The maxAge of this policy is the minimum maxAge across all fields in your request.

My initial expectation when testing this kind of setup:

```
cacheControl: {
    defaultMaxAge: 60
},

type Destination {
    name: String! @cacheControl(maxAge: 10)
    distance: Float!
}
```

would be for _Destination.distance_ to cache for 60 seconds, and _Destination.name_ to cache for 10. But the result is that the entire Destination type caches for the **minimum maxAge across all fields**, in this case 10.

**Comment by jbarefoot** [comment]
This is a bug.  The overall cache policy is documented correctly, yes, however the documentation is very specific that the default is that things are uncacheable:
>By default, root fields (ie, fields on Query and Mutation) and fields returning object and interface types are considered to have a maxAge of 0 (ie, uncacheable) if they don't have a static or dynamic cache hint.

The current behavior is that `@cache-control` doesn't work, period, unless you also set a `defaultMaxAge`.  That means you have to explicitly annotate every type you have with `@cache-control` and then set `defaultMaxAge` to something enormous, because of the overall cache policy logic.

I will say that the overall design approach here is fantastic!  This seems like it should be an easy thing to fix frankly.

**Comment by leonardoanalista** [comment]
Absolutely, I couldn't agree more. It's designed perfectly and we hope it gets fixed. I'll send this thread to the Apollo support team in several channels. Hopefully we get an answer soon.

**Comment by glasser** [comment]
defaultMaxAge is only supposed to be applied to root fields and object/interface fields (based on my memory and code inspection). The example in the initial issue above correctly applies a hint to the only root field which is also the only object field. So this should work and is a bug if it doesn't.

**Comment by glasser** [comment]
I implemented `apollo-server-plugin-response-cache` but my current focus isn't `apollo-server`. I am happy to look into and likely fix this if somebody can provide a full reproduction recipe: ie, a series of commands probably starting with `git clone` which allows me to see the bug without having to try to set up a server from scratch and guess all the details of what you tried.

**Comment by jbarefoot** [comment]
@glasser That's much appreciated, I'll try to find some time soon to create a basic repo that illustrates the issue.  In the meantime, I implemented a workaround which I'll post here for others.  The workaround is to use a wrapper function around every resolver function, that checks for a cache hint and adds it if it doesn't exist.  As long as you remember to use the wrapper on every query resolver, it works fine.  Then you set `defaultMaxAge` to something really high, like a day, so it will never be the minimum in the overall computed cache policy.

```
const defaultExpiry = 60  // in seconds
const defaultCacheHint = { maxAge: defaultExpiry, scope: 'PUBLIC' };

async function resolverWrapper(info, func) {
  console.log("Cache hint already set to:", info.cacheControl.cacheHint)

  // The hack here is that if cache-control has NOT been set for a type/field/whatever, then you will get { maxAge: 0 } for info.cacheControl.cacheHint i.e. uncached
  // If cache-control HAS been set, then you get { maxAge: <someInt>,  scope: undefined }, i.e. there will be a "scope" key
  // So only set default expiry/TTL if the "scope" key does NOT exist. (Checking for whether the cacheHint is defined is just being defensive)
  if(!info.cacheControl.cacheHint || !("scope" in info.cacheControl.cacheHint)) {
    console.log("Cache hint was NOT set so defaulting to:", defaultCacheHint)
    info.cacheControl.setCacheHint(defaultCacheHint);
  }
  return func()
}

// Use it from a resolver like this:
loadSomeThings: async (_, {fromDate, toDate}, __, info) => resolverWrapper(info, async () => {
  const sql = `select foo, bar, baz, start_date from some_table where start_date between '${fromDate}' and '${toDate}'`
  return await runMySQLQuery( sql )
}),

```

**Comment by glasser** [comment]
@jbarefoot How is that better than setting defaultMaxAge to 60?

**Comment by jbarefoot** [comment]
@glasser  It means you can have a short default expiry and override with longer values. The code I posted only sets the expiry to 60 if `@cache-control` has NOT been set.  Setting `defaultMaxAge` to 60 means if you have e.g. `@cache-control(300)`, it will get ignored and `defaultMaxAge` of 60 used instead, owing to the "min expiry wins" overall cache policy behavior.  The current behavior of `defaultMaxAge` makes it impossible to set a very short default expiry with selectively longer expiry for objects/fields that you know are safe to cache longer.  Frankly I disagree with this, if anything in the query graph has `@cache-control` set, IMO that should be used and `defaultMaxAge` ignored.  My general expectation is that more granular settings override more general/larger scope (though I'm not sure I would apply that to type vs field `@cache-control` usage here, I would have to think about it more).  

In my experience this is a common way to use a server cache:  The default expiry is pretty short or perhaps not cached (whatever is appropriate for the context).  For data that is slowly changing, set the expiry case-by-base to longer values.

**Comment by glasser** [comment]
That is not my understanding of how defaultMaxAge works (though of course, there may be a bug, that's why we're here).

If you set defaultMaxAge to 5 but have a schema like

```
type Query  {
  someField: Foo @cacheControl(maxAge: 50)
  someOtherField: Bar
}
```

Then queries against someField will be cached for 50, queries against someOtherField will be cached for 5, and queries that hit both fields will also be cached for 5 because they contain some low-TTL data. Is that not what you're experiencing?

The main feature that I think is missing here (other than features that would make this model more comprehensible/inspectable) is the ability to mark an object/interface field as "inherit parent maxAge" just like scalar fields do.

**Comment by jbarefoot** [comment]
@glasser Thanks for the reply. I wasn't testing field level caching, so I'm not sure on that.  I will try to test it later in my schema and let you know the result.  My object example would be like this:
```
type User @cache-control(maxAge:50)  {
  someField: Foo
  someOtherField: Bar
}
```
In the above case, with defaultMaxAge=5, if you fetch `User` by id, it will be cached for 5 seconds, not 50.

> the ability to mark an object/interface field as "inherit parent maxAge" just like scalar fields do.

Really I just want it to not use defaultMaxAge, at all, if a cache hint has been set, either via `@cache-control` or dynamically.  To me default means default, i.e. use this if there is no other value.  Instead the way it works in my testing is, override cache hint value with defaultMaxAge if it is less than what is currently computed, i.e. defaultMaxAge is the "uber parent" of the object graph.  I think that's what is throwing people for a loop here. 

And sorry yes let me try to get you an example git repo later this week, I know this is difficult without seeing a concrete thing that doesn't work as expected. :)

**Comment by matikucharski** [comment]
> Then queries against someField will be cached for 50, queries against someOtherField will be cached for 5, and queries that hit both fields will also be cached for 5 because they contain some low-TTL data. Is that not what you're experiencing?

It is how it should work but now `someField` field is cached also for 5 sec - not on 50 sec. Just tested it.

---
Btw it would be also great to have ability to set default scope on all queries to `PRIVATE`.
In my app they all should be 'PRIVATE' so I need to mark each individually to be 'PRIVATE' instead of setting it once eg like this:
```
cacheControl: {
  defaultMaxAge: 5,
  defaultScope: 'PRIVATE'
}
```

**Comment by eetvalve** [comment]
My solution (for now) was to make custom @CacheControl decorator (with type-graphql):

 `   import { UseMiddleware } from 'type-graphql';`

    export function CacheControl(hint: CacheHint) {
      return UseMiddleware(({ context, info }, next) => {
        console.log('Called CacheControl');

        context.cacheOptions = {
            ttl: hint.maxAge,
        };
      
      // replace with setCacheHint when it is working properly again
      // info.cacheControl.setCacheHint(hint);
        return next();
      });
    }

`@CacheControl({ maxAge: 60 })`

Obviously `scope: private/public` is missing from `context.cacheOptions` but many times setting `ttl` is enough.

Tested only with `type-graphql` -module

**Comment by chrislambe** [comment]
This was very confusing. I expected to be able to override `defaultMaxAge` completely (not just providing a lesser value). It's not clear from the documentation that this is the case.

**Comment by glasser** [comment]
I still do not understand what the complaint is in this bug and will launch into fixing it as soon as somebody presents a self-contained reproduction!

**Comment by terryf82** [comment]
@glasser I'm not sure exactly what you need for a self-contained reproduction, but I feel my initial comment on expected vs actual behaviour describes the issue most here are experiencing:

> My initial expectation when testing this kind of setup:
> 
> ```
> cacheControl: {
>     defaultMaxAge: 60
> },
> 
> type Destination {
>     name: String! @cacheControl(maxAge: 10)
>     distance: Float!
> }
> ```
> 
> would be for _Destination.distance_ to cache for 60 seconds, and _Destination.name_ to cache for 10. But the result is that the entire Destination type caches for the **minimum maxAge across all fields**, in this case 10.

If I can offer anything further that might help, please let me know.

**Comment by glasser** [comment]
As I said above:

 a full reproduction recipe: ie, a series of commands probably starting with git clone which allows me to see the bug without having to try to set up a server from scratch and guess all the details of what you tried. (For example, this should include a sample query and some way to tell that it's not cached (perhaps a resolver that returns random values).)

**Comment by terryf82** [comment]
@glasser my example is unlikely to be useful to you then, we're using the neo4j-graphql-js package which requires no resolvers to be written, just types defined.

The amount of interest in this thread clearly indicates a problem though, so hopefully someone can move this forward by supplying what you need.

**Comment by mattvb91** [comment]
Came across the same issue here that my schema cache hints were not being set and no cache headers sent out at all. Fixed it with the suggestion above of defining a defaultMaxAge

```
 cacheControl: {
    defaultMaxAge: 60
},
```

This is more of a hack than anything to have any sort of caching headers sent out but will surely cause issues down the line

**Comment by sanketCactus** [comment]
Facing similar issue, 
when I use caching at the Apollo server level then everything is cached I can see no DB queries in log after the first request. Caching seems to be working 

```
 cacheControl: {
    defaultMaxAge: 60
},
```

But when I try the fine grain caching at resolvers I can see the maxAge set in HTTP response but the response doesn't seem to be cached as I can see DB queries on each request 

```
const resolvers = {
  Query: {
    post: (_, { id }, _, info) => {
      info.cacheControl.setCacheHint({ maxAge: 60, scope: 'PUBLIC' });
      return find(posts, { id });// some db call
    }
  }
}
```

Am I doing anything wrong here?

**Comment by glasser** [comment]
Please provide a full executable reproduction example, as described in my previous comments on this issue.

**Comment by stevez86** [comment]
@glasser PR submitted to fix this issue: https://github.com/apollographql/apollo-server/pull/4162

**Comment by stevez86** [comment]
@glasser Apologies that PR may have been a bit premature as I wasn't sure of the reasoning of some of the tests. Here is a reproduction I think encompasses some of the issues above (not sure why they couldn't create a repro themselves). 

```javascript
// type-defs.js
    type Foo {
        id: ID!
        name: String!
    }
    
  type User {
    id: ID!
    name: String!
    status: String!
      foo: Foo!
  }

  type Query {
    viewer: User
    fooUser: User @cacheControl(maxAge: 100)
  }
```

I would expect the fooUser to be cached for 100 but because Foo is its child, the defaultMaxAge of 0 gets applied to it and then the cache is calculated to be 0 when calculating the smallest maxAge.

My PR (ref above) attempted to address this by applying the `defaultMaxAge` when no `maxAge` was set, which is what I think most people expected the behavior to be and why there is some confusion around this. The PR fixed my use cases but obviously failed some of the tests.

**Comment by stevez86** [comment]
Throwing out ideas and thinking about this further, is there any reason why individual fields need a maxAge cache while computing?  

Maybe we don't default the defaultMaxAge to 0 here: https://github.com/apollographql/apollo-server/blob/7d6f23443e52a90deb74f152f34bb76eea78ee19/packages/apollo-cache-control/src/index.ts#L57

and do this:

```javascript
constructor(public options: CacheControlExtensionOptions = {}) {
    this.defaultMaxAge = options.defaultMaxAge;
  }
```

or maybe add `&& this.defaultMaxAge > 0` here: https://github.com/apollographql/apollo-server/blob/7d6f23443e52a90deb74f152f34bb76eea78ee19/packages/apollo-cache-control/src/index.ts#L103
 
like so:
```javascript
    if (
      (targetType instanceof GraphQLObjectType ||
        targetType instanceof GraphQLInterfaceType ||
        !info.path.prev) &&
      hint.maxAge === undefined && this.defaultMaxAge > 0
    ) {
      hint.maxAge = this.defaultMaxAge;
    }
```

IMO the default should be applied at the end like in my PR but not sure why some of these test cases are needed:
https://github.com/apollographql/apollo-server/blob/7d6f23443e52a90deb74f152f34bb76eea78ee19/packages/apollo-cache-control/src/__tests__/cacheControlDirective.test.ts#L6

**Comment by Yunoo** [comment]
I assume that `this.maxAge` should always be an integer and something might break if it's a `null` or `undefined`. That's what I experienced when I was trying to fix this issue last year.
Correct me if I am wrong. Otherwise, the only reason for always setting maxAge to 0 that I can think of is to enforce a developer to explicitly set TTL on every type to avoid unexpected caching behaviour.

**Comment by mthenw** [comment]
I think that I have the same issue with the `cache-control` header not set when `defaultMaxAge` is not defined. @glasser here is a repo with a detailed reproduction recipe. Let me know if something is not clear. 

https://github.com/mthenw/apollo-cache-issue

**Comment by glasser** [comment]
@mthenw: According to the docs at https://www.apollographql.com/docs/apollo-server/api/apollo-server/

> If set to true, adds tracing or cacheControl metadata to the GraphQL response. This is primarily intended for use with the deprecated Engine proxy. cacheControl can also be set to an object to specify arguments to the apollo-cache-control package, including defaultMaxAge, calculateHttpHeaders, and stripFormattedExtensions.

As documented, `cacheControl: true` literally just includes this somewhat useless metadata in the GraphQL response. This was something we implemented before we implemented writing caching HTTP response headers, so we wanted to keep its behavior consistent even as we changed the default for users who don't specify `cacheControl` at all.

The logic in the code is:

```
    if (this.config.cacheControl !== false) {
      let cacheControlOptions: CacheControlExtensionOptions = {};
      if (
        typeof this.config.cacheControl === 'boolean' &&
        this.config.cacheControl === true
      ) {
        // cacheControl: true means that the user needs the cache-control
        // extensions. This means we are running the proxy, so we should not
        // strip out the cache control extension and not add cache-control headers
        cacheControlOptions = {
          stripFormattedExtensions: false,
          calculateHttpHeaders: false,
          defaultMaxAge: 0,
        };
      } else {
        // Default behavior is to run default header calculation and return
        // no cacheControl extensions
        cacheControlOptions = {
          stripFormattedExtensions: true,
          calculateHttpHeaders: true,
          defaultMaxAge: 0,
          ...this.config.cacheControl,
        };
      }
```

Are there docs somewhere that encouraged you to set `cacheControl: true` that we should fix?

**Comment by mthenw** [comment]
@glasser ohh, I get it now. Thank you!

Regarding the metadata, I think it's a bit confusing that it says:
```
"extensions": {
    "cacheControl": {
      "version": 1,
      "hints": [
        {
          "path": [
            "books"
          ],
          "maxAge": 100
        }
      ]
    }
  }
```
 (no other hint with maxAge:0) and the header is still not set. 

Going back to my example (https://github.com/mthenw/apollo-cache-issue). It's totally not clear (after reading docs for a few times) where should I put the `@cacheControl` directive to cache this query (without changing global defaultMaxAge):
```
{
  books{
    title
  }
}
```
If I define it for the `Book` type it clearly doesn't work and the header is not set even though the response doesn't contain any other object/type.

**Comment by glasser** [comment]
Applying this diff to your repo and running your curl command, the header is set to 100.

```diff
diff --git a/index.js b/index.js
index 4533fd6..eda16c5 100644
--- a/index.js
+++ b/index.js
@@ -1,7 +1,7 @@
 const { ApolloServer, gql } = require("apollo-server");
 
 const typeDefs = gql`
-  type Book { #@cacheControl(maxAge: 100)
+  type Book @cacheControl(maxAge: 100) {
     title: String
     author: String
   }
@@ -31,10 +31,6 @@ const resolvers = {
 const server = new ApolloServer({
   typeDefs,
   resolvers,
-  cacheControl: {
-    defaultMaxAge: 1000,
-  },
-  // cacheControl: true,
 });
 
 // The `listen` method launches a web server.
```

The point is that passing `true` for cacheControl enables a backwards-compatibility mode that you don't want, but just leaving it out (or specifying an object with other options in it) gives the result you want.

Definitely a lesson here about the naming of boolean options: we should have been more thoughtful and named it `includeCacheControlExtension` or `cacheControl: {includeExtension}`.

**Comment by SachaG** [comment]
After reading through parts of this thread I'm still pretty confused, and I can't tell if Apollo Server is not working at it should; or else if I just don't understand what it's supposed to do. 

To clarify, if I add this at the top of a resolver:

```
cacheControl.setCacheHint({ maxAge: 300 });
console.log('hello world!');
```

I would expect subsequent queries to that resolver to not execute the `console.log` for the next five minutes? If so then that's not what I'm seeing currently.

**Comment by glasser** [comment]
Hi @SachaG !

As mentioned above it is very challenging for me to provide support on this feature just based on single line snippets, rather than complete examples.

`apollo-server-plugin-response-cache` is a *full response* cache that caches full GraphQL responses if every field queried in it is cacheable. So if a query asks for a cacheable field and an uncacheable field, it will re-run the resolver for the cacheable field too because the whole response is not cacheable.

**Comment by SachaG** [comment]
Sorry, I was actually asking about the [Adding cache hints dynamically in your resolvers](https://www.apollographql.com/docs/apollo-server/performance/caching/#adding-cache-hints-dynamically-in-your-resolvers) feature, which seems different from the full response cache? Since some people were posting similar code snippets here I thought maybe they were related. But to clarify I am not (yet) using the `apollo-server-plugin-response-cache` package, so maybe my question should be in another thread.

**Comment by glasser** [comment]
`setCacheHint` is a mechanism for defining the cache-ability of a resolver's output; the `@cacheControl` directive in schemas is another mechanism for the same thing.  This metadata is an input into several cache-related features, like the calculation of `cache-control` HTTP headers on responses and the full response cache plugin, but is not itself a cache.

**Comment by SachaG** [comment]
> This metadata is an input into several cache-related features, like the calculation of cache-control HTTP headers on responses and the full response cache plugin, but is not itself a cache.

Oh, does this mean that setting the metadata by itself should not be expected to actually cache the data? If so that would explain why I didn't notice any difference in my implementation. If that's the case maybe the docs could state this explicitly, it might be confusing for others as well?

**Comment by Morganjackson** [comment]
@SachaG  The only way I can get the resolver cache hints working is if I set `cacheControl` with the `defaultMaxAge` option set higher than the resolver hint otherwise its ignored.  Strangely the `@cacheControl` directive works as expected without the `cacheControl` set.

**Comment by xenoterracide** [comment]
> The point is that passing true for cacheControl enables a backwards-compatibility mode that you don't want, but just leaving it out (or specifying an object with other options in it) gives the result you want.

for us `@cacheControl` was not working AT ALL, the only thing that seem was working was the `defaultMaxAge` setting this seems to have fixed the problem... or maybe it's not setting this, but setting it this way instead...

```
  cacheControlOptions = { defaultMaxAge: parseInt(this.cacheMaxAge) };
```

I'd like to mention that it's also non obvious what granularity these options are, I'm guessing seconds?

I'd also like to say that I don't like how it works out of the box, I really don't want to annotate everything ever.

**Comment by SachaG** [comment]
@glasser I might be wrong but I get the impression this is maybe more an issue with unclear documentation than an actual bug? I haven't had time to revisit this issue but now I just learned about [datasources](https://www.apollographql.com/docs/apollo-server/data/data-sources/) and I feel like that's one more caching parameter I need to juggle with… I think a comprehensive blog post or example app that clearly outlines the different caching methods available with Apollo Server and the pros and cons of each one would be helpful here.

**Comment by SachaG** [comment]
To follow up on my last post, I only just now finally understood that this is about setting cache hints so that Apollo can figure out whether the *entire* request is cacheable or not; and not telling Apollo to cache individual fields. 

In other words, if I have 9 cached fields and 1 uncacheable fields in my request I falsely expected after reading the documentation that those 9 fields would be cached and not trigger database, API, etc. requests. Whereas the truth (as I now understand it, I might still be wrong?) is that *none* of my 10 fields will be cached because the entire request is not cacheable. 

On the other hand, if I used Datasources for those 9 fields then those database, API, etc. requests *would* be cached independently of whether the full GraphQL can be cached or not. 

Again sorry if I'm wrong and just making things more confusing, but I suspect other people might've misunderstood this as well.

**Comment by glasser** [comment]
@SachaG So there's two separate things.

Apollo Server has a flexible way of assigning cache hints on a per-field basis.

AS then uses that data to power several features. Right now, the only features that makes use of this data are full-response features, such as the full response cache (https://www.apollographql.com/docs/apollo-server/performance/caching/#saving-full-responses-to-a-cache) and HTTP response header calculations.

One could imagine building out a partial response cache as well! In a lot of cases this will require a way for the server to know how to "jump" deep into a query to re-query just the changing data. We have not built that and I do not believe it is on any particular roadmap, but it is an imaginable way to make use of the detailed per-field cache data.

Datasources is basically unrelated. It's a fancy word for "we built a caching HTTP client in Node, maybe that's useful for you when writing your resolvers".  Also note that there are two different things called "data sources" in GraphQL (the caching HTTP client thing and the interface that Apollo Gateway uses to talk to implementing services).

**Comment by SachaG** [comment]
> One could imagine building out a partial response cache as well! In a lot of cases this will require a way for the server to know how to "jump" deep into a query to re-query just the changing data. We have not built that and I do not believe it is on any particular roadmap, but it is an imaginable way to make use of the detailed per-field cache data.

Yes, I saw this issue about that: https://github.com/apollographql/apollo-server/issues/4042

> Datasources is basically unrelated. It's a fancy word for "we built a caching HTTP client in Node, maybe that's useful for you when writing your resolvers". Also note that there are two different things called "data sources" in AS (the caching HTTP client thing and the interface that Apollo Gateway uses to talk to implementing services) that are also unrelated.

Good to know, thanks for the added details!

**Comment by aonamrata** [comment]
Hi @SachaG 

About this part :point_down: 
> On the other hand, if I used Datasources for those 9 fields then those database, API, etc. requests _would_ be cached independently of whether the full GraphQL can be cached or not.

Do you know how I can implement this or what package are you referring to? I am using REST datasource so if I can do this, then I don't need the field/type level cache control. This would behave the same for 90% of my cases. FYI, not ttl as that is only for a request so not really useful across requests.

**Comment by SachaG** [comment]
> Hi @SachaG
> 
> About this part 👇
> 
> > On the other hand, if I used Datasources for those 9 fields then those database, API, etc. requests _would_ be cached independently of whether the full GraphQL can be cached or not.
> 
> Do you know how I can implement this or what package are you referring to? I am using REST datasource so if I can do this, then I don't need the field/type level cache control. This would behave the same for 90% of my cases. FYI, not ttl as that is only for a request so not really useful across requests.

I don't know any more than what's in the [docs](https://www.apollographql.com/docs/apollo-server/data/data-sources/) and what @glasser mentioned, sorry. I haven't implemented them myself yet.

**Comment by mattvb91** [comment]
> Applying this diff to your repo and running your curl command, the header is set to 100.
> 
> ```diff
> diff --git a/index.js b/index.js
> index 4533fd6..eda16c5 100644
> --- a/index.js
> +++ b/index.js
> @@ -1,7 +1,7 @@
>  const { ApolloServer, gql } = require("apollo-server");
>  
>  const typeDefs = gql`
> -  type Book { #@cacheControl(maxAge: 100)
> +  type Book @cacheControl(maxAge: 100) {
>      title: String
>      author: String
>    }
> @@ -31,10 +31,6 @@ const resolvers = {
>  const server = new ApolloServer({
>    typeDefs,
>    resolvers,
> -  cacheControl: {
> -    defaultMaxAge: 1000,
> -  },
> -  // cacheControl: true,
>  });
>  
>  // The `listen` method launches a web server.
> ```
> 
> The point is that passing `true` for cacheControl enables a backwards-compatibility mode that you don't want, but just leaving it out (or specifying an object with other options in it) gives the result you want.
> 
> Definitely a lesson here about the naming of boolean options: we should have been more thoughtful and named it `includeCacheControlExtension` or `cacheControl: {includeExtension}`.

@glasser I have played around with this sample now and it does indeed work with your diff. However as soon as I make the following change it stops working and I think thats where the confusion comes from for a lot of people:

```
const typeDefs = gql`
  type Book @cacheControl(maxAge: 100) { 
    title: String
    author: String
    nestedObject: Object     #<--- this nestedObject will break it 
  }

  type Query {
    books: [Book]
  }

  type Object {
    test: Boolean
  }
`;

const books = [
  {
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    nestedObject: {
      test: true
    }
  },
  {
    title: "Jurassic Park",
    author: "Michael Crichton",
    nestedObject: {
      test: true
    }
  },
];

```

My assumption would be that the `Book` type would return maxAge of 100 in that case. However that does not happen until I also add `@cacheControl(maxAge: 100) ` to my `Object` type:

```
  type Object @cacheControl(maxAge: 100)  {
    test: Boolean
  }
```

Only then does the `cache-control: max-age=100, public` get sent for Book. Can you confirm this is expected behaviour?

**Comment by mattvb91** [comment]
Ok this is pretty embarrasing but here we go...

I was testing inside the GraphQL playground the whole time and viewing the requests through dev console network tab... Now I had assumed that the playground would automatically set the correct header for me which is: 

```
{
  "Accept": "application/json"
}
```

Once I have that in my headers in GraphQL Playground everything seems to be working fine... Only noticed this when curling the same queries and seeing a difference in headers.. 

I suggest everyone recheck their responses through curl and compare.

**Comment by mattvb91** [comment]
@glasser I have a repo with reproduction for you: https://github.com/mattvb91/apollo-cache-issue-reproduction

My assumption is caching will not work top level unless all sub nested objects have a caching hint on them.

**Comment by glasser** [comment]
@mattvb91 I'll dig in on your reproduction, but I do think you're observing documented behavior. https://www.apollographql.com/docs/apollo-server/performance/caching/#setting-a-default-maxage says:

> By default, root fields (ie, fields on Query and Mutation) and fields returning object and interface types are considered to have a maxAge of 0 (ie, uncacheable) if they don't have a static or dynamic cache hint.

nestedObject is a field returning an object type is its default maxAge is 0.

Whether this design for `@cacheControl`'s defaults is a *good idea* is a different question, but I'm pretty sure this is working exactly as intended?

**Comment by glasser** [comment]
Yes, looking at your reproduction, this is working as intended. The theory when designing this feature was that object fields are more likely to be "looking up a different thing with different cacheability" than scalar fields.  I'm not sure that this area of the product is under enough active development for it to be likely to change the semantics at this point.

**Comment by mattvb91** [comment]
Ah i think i may have gotten that confused then in thinking the removal of `defaultMaxAge` would allow the max age to be taken from the parent then.

 Yea it does seem to be more a discussion of wether that is a good default behaviour. Thanks

**Comment by macrozone** [comment]
i also struggle with this problem.

We want to define some named root queries that should be cached (the full response), but the default should be no-cache.

There is no combination of setting the `defaultMaxAge` and individual cache hints that seem to be correct. defaultMaxAge in fact is the only thing that seems to have an impact.

If someone could point me int the right direction, i would be very glad.

**Comment by macrozone** [comment]
I also noticed that only the first query has the right cacheHint:

- i define a defaultMaxAge of 3600 (without it, it does not work at all)
- on a field i add a cachehint of 60 (1min)
- i run the query twice and inspect both the headers and whether my db request is performed)

first request responses with `cache-control: max-age=60, public`
second request responses with `cache-control: max-age=3600, public`

it seems like apollo server caches the cache hints as well!

**Comment by ankuradhey** [comment]
I tried without defaultMaxAge and caching is working for me. I noticed that whenever we are missing nested fields' cache control hints then it tries to use defaultMaxAge and which is 0 by default. Hence, it looks like caching is not working. 

Some points to be noted
-  Resolver level caching policy takes higher precedence than schema-object level
-  Lowest cache expiration takes highest precedence
-  Responses containing GraphQL errors or no data are never cached

**Comment by timsuchanek** [comment]
In case you want to save the effort of setting up Redis, getting the config working etc,
you may wanna have a look at https://graphcdn.io.
I'm building that right now, especially to make caching easier, as I struggled with it myself before.

**Comment by koborg** [comment]
> I tried without defaultMaxAge and caching is working for me. I noticed that if we are not using cache control hints properly then it looks like it is not working. Make sure that cache hint is applied to a field and its nested non scalar fields as well then only caching will work. Otherwise when it finds nested non scalar field is missing cache control so it tries to use defaultMaxAge and which is 0 by default. Hence, it looks like caching is not working.
> 
> Some points to be noted
> 
> * Resolver level caching policy takes higher precedence than schema-object level
> * Lowest cache expiration takes highest precedence
> * Responses containing GraphQL errors or no data are never cached

HUGE THANKS ankuradhey!!!
Your comment lightened up my implementation!
So... if we want defaultMaxAge: 0, than we need to explicitly define the @cacheControl(maxAge: XXX) directive to all non scalar fields of the respected query or mutation. Once I did that, the all the fields marked with the directive started to respect the the defined maxAge and all the other fields (non marked) remained with 0 caching time.

**Comment by glasser** [comment]
Here's an implementation of something that's similar to the `inherit` concept I discussed above: https://github.com/apollographql/apollo-server/pull/5247
I'm interested in feedback from folks who were interested in this issue!

**Comment by glasser** [comment]
I think the main concern in this issue is addressed in #5247.
